<a href="https://colab.research.google.com/github/ktonon0401/AI-training/blob/main/lesson3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
import numpy as np
# x=[[-0.5,-0.3],[-0.5,0.5],[0.3,-0.3],[0.1,1]] # 4 mẫu dữ liệu, 2 đầu vào
# x=[[0.8,0.8],[-0.5,0.3],[]]
# x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.3],[0.1,1],[0.8,0.2],[0.4,-0.1]]
x=[[0,1],[1,0],[1,1],[0,0]]
# y=[1,1,1,0]
# y=[1,1,0,0] 

model=Perceptron(max_iter= 40,eta0= 0.1,random_state= 0)
model.fit(x,y)
model.predict(x)


array([1, 1, 1, 0])

In [ ]:
y = [1,1,1,0]
model.fit(x,y)
model.score(x,y)

1.0

In [ ]:
x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[0.1,1],[0.8,0.2],[0.4,-0.1]]
y_pred=model.predict(x)
model=Perceptron(max_iter= 40,eta0= 0.1,random_state= 0)

model.fit(x,y_pred)
model.score(x,y_pred)

1.0

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
X = iris.data
Y = iris.target

In [ ]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
Y[:5]

array([0, 0, 0, 0, 0])

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [ ]:
model.fit(X_train,Y_train)
model.score(X_train,Y_train)

0.5714285714285714

In [ ]:
model.fit(X_test,Y_test)
model.score(X_test,Y_test)

0.8222222222222222

In [ ]:
X[95:101]

array([[5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5]])

In [ ]:
model=Perceptron(max_iter= 40,eta0= 0.1,random_state= 0)
X=[[3. , 4.2],[2.9, 4.2],
       [2.9, 4.3],
       [2.5, 3.],
       [2.8, 4.1],
       [3.3, 6.]]
model.predict(X)

NotFittedError: ignored

In [196]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

data=pd.read_csv('drive/MyDrive/Colab Notebooks/data_crab.csv')

In [197]:
data

sp sex  index    FL    RW    CL    CW    BD
0    B   M      1   8.1   6.7  16.1  19.0   7.0
1    B   M      2   8.8   7.7  18.1  20.8   7.4
2    B   M      3   9.2   7.8  19.0  22.4   7.7
3    B   M      4   9.6   7.9  20.1  23.1   8.2
4    B   M      5   9.8   8.0  20.3  23.0   8.2
..  ..  ..    ...   ...   ...   ...   ...   ...
195  O   F     46  21.4  18.0  41.2  46.2  18.7
196  O   F     47  21.7  17.1  41.7  47.2  19.6
197  O   F     48  21.9  17.2  42.6  47.4  19.5
198  O   F     49  22.5  17.2  43.0  48.7  19.8
199  O   F     50  23.1  20.2  46.2  52.5  21.1

[200 rows x 8 columns]

In [309]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import Perceptron
data = pd.read_csv('drive/MyDrive/Colab Notebooks/data_crab.csv')
data = data.loc[data.sp=='B']
data = data.replace('M',1)
data = data.replace('F',0)
x = data.drop(['sp','sex','index'],axis = 1)
y = data['sex']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron( max_iter = 40 , eta0= 0.1, random_state= 0)





In [310]:
data

sp  sex  index    FL    RW    CL    CW    BD
0   B    1      1   8.1   6.7  16.1  19.0   7.0
1   B    1      2   8.8   7.7  18.1  20.8   7.4
2   B    1      3   9.2   7.8  19.0  22.4   7.7
3   B    1      4   9.6   7.9  20.1  23.1   8.2
4   B    1      5   9.8   8.0  20.3  23.0   8.2
.. ..  ...    ...   ...   ...   ...   ...   ...
95  B    0     46  16.4  14.0  34.2  39.8  15.2
96  B    0     47  16.7  16.1  36.6  41.9  15.4
97  B    0     48  17.4  16.9  38.2  44.1  16.6
98  B    0     49  17.5  16.7  38.6  44.5  17.0
99  B    0     50  19.2  16.5  40.9  47.9  18.1

[100 rows x 8 columns]

In [311]:
model.fit(x_train,y_train)
model.score(x_train,y_train)

0.8

In [312]:
model.fit(x_test,y_test)
model.score(x_test,y_test)

0.8666666666666667

In [313]:
y_hat = model.predict(x_test)
cal = pd.DataFrame(np.c_[y_test,y_hat],columns=['y_test','y_hat'])
cal

y_test  y_hat
0        0      0
1        0      0
2        0      1
3        1      1
4        1      1
5        1      1
6        0      0
7        0      0
8        1      1
9        0      1
10       1      1
11       0      1
12       1      1
13       0      0
14       0      0
15       0      1
16       1      1
17       1      1
18       1      1
19       1      1
20       1      1
21       0      0
22       1      1
23       0      0
24       1      1
25       1      1
26       0      0
27       0      0
28       1      1
29       1      1